/**
 * Seed Data — Google Sheets Initial Data
 *
 * Copy these rows into the corresponding sheets in the Google Spreadsheet.
 * First row of each sheet = headers (must match USERS_COLS, HOSPITAL_COLS etc. in Code.gs).
 *
 * USAGE: Open Google Spreadsheet → select sheet → paste rows starting from row 2
 */

// ---------------------------------------------------------------------------
// HOSPITAL sheet (16 facilities: สสอ. + รพ. + 14 รพ.สต.)
// Headers: hosp_code | hosp_name | hosp_type | active
// ---------------------------------------------------------------------------
const HOSPITAL_SEED = [
  ['00588', 'สสอ.สอง', 'สสอ.', 'Y'],
  ['11111', 'รพ.สอง', 'รพ.', 'Y'],
  ['10669', 'รพ.สต.นาหลวง', 'รพ.สต.', 'Y'],
  ['10670', 'รพ.สต.ป่าตาราง', 'รพ.สต.', 'Y'],
  ['10671', 'รพ.สต.บ้านโป่ง', 'รพ.สต.', 'Y'],
  ['10672', 'รพ.สต.ห้วยอิตน์', 'รพ.สต.', 'Y'],
  ['10673', 'รพ.สต.นาทราย', 'รพ.สต.', 'Y'],
  ['10674', 'รพ.สต.บ้านแพะ', 'รพ.สต.', 'Y'],
  ['10675', 'รพ.สต.วังช้าง', 'รพ.สต.', 'Y'],
  ['10676', 'รพ.สต.ทุ่งโพธิ์', 'รพ.สต.', 'Y'],
  ['10677', 'รพ.สต.ห้วยน้ำคำ', 'รพ.สต.', 'Y'],
  ['10678', 'รพ.สต.ดอยคำ', 'รพ.สต.', 'Y'],
  ['10679', 'รพ.สต.แม่ทราย', 'รพ.สต.', 'Y'],
  ['10680', 'รพ.สต.แจ้ห่ม', 'รพ.สต.', 'Y'],
  ['10681', 'รพ.สต.เมืองลี', 'รพ.สต.', 'Y'],
  ['10682', 'รพ.สต.สบเมย', 'รพ.สต.', 'Y'],
]

// ---------------------------------------------------------------------------
// FACILITIES sheet (15 รพ.สต. — same as HOSPITAL minus สสอ. and รพ.)
// Headers: hosp_code | hosp_name | contact_name | contact_tel | active
// ---------------------------------------------------------------------------
const FACILITIES_SEED = [
  ['10669', 'รพ.สต.นาหลวง', '', '', 'Y'],
  ['10670', 'รพ.สต.ป่าตาราง', '', '', 'Y'],
  ['10671', 'รพ.สต.บ้านโป่ง', '', '', 'Y'],
  ['10672', 'รพ.สต.ห้วยอิตน์', '', '', 'Y'],
  ['10673', 'รพ.สต.นาทราย', '', '', 'Y'],
  ['10674', 'รพ.สต.บ้านแพะ', '', '', 'Y'],
  ['10675', 'รพ.สต.วังช้าง', '', '', 'Y'],
  ['10676', 'รพ.สต.ทุ่งโพธิ์', '', '', 'Y'],
  ['10677', 'รพ.สต.ห้วยน้ำคำ', '', '', 'Y'],
  ['10678', 'รพ.สต.ดอยคำ', '', '', 'Y'],
  ['10679', 'รพ.สต.แม่ทราย', '', '', 'Y'],
  ['10680', 'รพ.สต.แจ้ห่ม', '', '', 'Y'],
  ['10681', 'รพ.สต.เมืองลี', '', '', 'Y'],
  ['10682', 'รพ.สต.สบเมย', '', '', 'Y'],
]

// ---------------------------------------------------------------------------
// SETTINGS sheet (default key-value pairs)
// Headers: key | value
// ---------------------------------------------------------------------------
const SETTINGS_SEED = [
  ['bot_token', ''],
  ['chat_id', ''],
  ['alert_time', '07:00'],
  ['system_name', 'Telemed Tracking คปสอ.สอง'],
  ['telegram_active', 'N'],
  ['app_url', 'https://telemed-song.pages.dev'],
]

// ---------------------------------------------------------------------------
// MASTER_DRUGS sheet (initial drug list)
// Headers: drug_id | drug_name | strength | unit | active
// ---------------------------------------------------------------------------
const MASTER_DRUGS_SEED = [
  ['', 'Paracetamol', '500 mg', 'Tablet', 'Y'],
  ['', 'Amlodipine', '5 mg', 'Tablet', 'Y'],
  ['', 'Losartan', '50 mg', 'Tablet', 'Y'],
  ['', 'Metformin', '500 mg', 'Tablet', 'Y'],
  ['', 'Simvastatin', '20 mg', 'Tablet', 'Y'],
  ['', 'Omeprazole', '20 mg', 'Capsule', 'Y'],
  ['', 'Cetirizine', '10 mg', 'Tablet', 'Y'],
  ['', 'Amoxicillin', '500 mg', 'Capsule', 'Y'],
  ['', 'Diclofenac', '50 mg', 'Tablet', 'Y'],
  ['', 'Prednisolone', '5 mg', 'Tablet', 'Y'],
  ['', 'Salbutamol', '2 mg', 'Tablet', 'Y'],
  ['', 'Ibuprofen', '400 mg', 'Tablet', 'Y'],
  ['', 'Chlorpheniramine', '4 mg', 'Tablet', 'Y'],
  ['', 'Ranitidine', '150 mg', 'Tablet', 'Y'],
  ['', 'Diazepam', '5 mg', 'Tablet', 'Y'],
]

// NOTE: drug_id will be auto-generated by GAS (Utilities.getUuid()) on first import.
// Leave drug_id column empty; use GAS masterDrug.import action to batch-insert.
